# Generated by Django 5.0.7 on 2024-07-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_second_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='second',
            name='image',
            field=models.ImageField(default='exit', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='second',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='second',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.second')),
            ],
        ),
    ]
