# Generated by Django 5.0.7 on 2024-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='Default Name', max_length=255, null=True),
        ),
    ]
