# Generated by Django 5.0.7 on 2024-07-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
